### ISSUE TITLE
Left Side DPad does nothing

### ISSUE THREAD

**Issue by trevorsargent** [Castor-o7/pokedex#1]
EXPECTED: 
Based on the readme, left side dPad should change selected pokenmon

ACTUAL: 
dPad does nothing

REPRODUCTION: 
[Try DPad](https://pokedex-6n6wmvwax-castor-o7.vercel.app/)

**Comment by Castor-o7** [comment]
Pushed dPad functionality, thank you!

<a href="https://pokedex-teal-one.vercel.app/">Updated Pokedex</a>
